# WERF version for CI workflows. Read at runtime from this file by read_werf_version_step.
WERF_VERSION: "v2.73.2"
WERF_LOG_QUIET: "true"
WERF_LOG_PRETTY: "false"
WERF_LOG_VERBOSE: "false"
WERF_LOG_DEBUG: "false"
WERF_LOG_COLOR_MODE: "off"
WERF_LOG_TIME: "false"
{!{ define "werf_envs" }!}
# <template: werf_envs>
WERF_ENV: "FE"
TEST_TIMEOUT: "15m"
# Use fixed string 'sys/deckhouse-oss' for repo name. ${CI_PROJECT_PATH} is not available here in GitHub.
REGISTRY_PATH: "sys/deckhouse-oss"
# Registry for additional repositories used for testing Github Actions workflows.
GHA_TEST_REGISTRY_PATH: "ghcr.io/${{ github.repository }}"
# Need for ssh: default.
DOCKER_BUILDKIT: "1"
WERF_FINAL_IMAGES_ONLY: true
WERF_LOG_TERMINAL_WIDTH: "500"
WERF_GIT_WORK_TREE_POOL_LIMIT: "10"
GOPROXY: "${{vars.GOPROXY}}"
# </template: werf_envs>
{!{- end -}!}
